[versions]
kotlin = "1.8.10"
blocking-bridge = "3.0.0-180.1"
junit-bom = "5.9.1"
jackson = "2.18.2"
spigot = "1.20.1-R0.1-SNAPSHOT"

coroutines-core = "1.8.0"
byte-buddy = "1.15.10"

type-resolver = "0.1.0-SNAPSHOT"

shadow = "8.3.5"
slf4j = "2.0.16"
log4j = "2.24.3"

[libraries]
type-resolver = { module = "cn.chuanwise:kotlin-type-resolver", version.ref = "type-resolver" }

blocking-bridge-runtime = { module = "me.him188:kotlin-jvm-blocking-bridge-runtime", version.ref = "blocking-bridge" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-bom" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-core" }
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }

byte-buddy = { module = "net.bytebuddy:byte-buddy", version.ref = "byte-buddy" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
log4j-sl4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
blocking-bridge = { id = "me.him188.kotlin-jvm-blocking-bridge", version.ref = "blocking-bridge" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
